###############################################################################
# Copyright (c) 2022-25, Lawrence Livermore National Security, LLC and RADIUSS
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
###############################################################################

variables:
##### LC GITLAB CONFIGURATION
  LLNL_SERVICE_USER: ""
  GIT_SUBMODULE_STRATEGY: none

##### PROJECT VARIABLES
  BUILD_ROOT: ${CI_PROJECT_DIR}

##### SHARED_CI CONFIGURATION
  GITHUB_PROJECT_NAME: "test-performance-project"
  GITHUB_PROJECT_ORG: "LLNL"
  JOB_CMD:
    value: "./ci_script.sh"
    expand: false

# High level stages
stages:
  - prerequisites
  - build-and-test
  - performance-measurements

# Performance pipeline.
performance-measurements:
  stage: performance-measurements
  trigger:
    include:
      - local: '.gitlab/custom-jobs-and-variables.yml'
      - project: 'radiuss/radiuss-shared-ci'
        ref: 'woptim/caliper-ci'
        file: 'pipelines/performances.yml'
      - local: '.gitlab/jobs/performances.yml'
    strategy: depend
    forward:
      pipeline_variables: true

include:
  # Sets ID tokens for every job using `default:`
  - project: 'lc-templates/id_tokens'
    file: 'id_tokens.yml'
  # [Optional] checks preliminary to running the actual CI test
  # - project: 'radiuss/radiuss-shared-ci'
  #   ref: 'v2025.07.0'
  #   file: 'utilities/preliminary-ignore-draft-pr.yml'
  # # pipelines subscribed by the project
  # - local: '.gitlab/subscribed-pipelines.yml'